/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    Breadcrumb: typeof import('./src/components/Layout/components/RightContent/comp/Breadcrumb.vue')['default']
    Header: typeof import('./src/components/Layout/components/Header/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    LayoutSlot: typeof import('./src/components/Layout/components/LayoutSlot.vue')['default']
    LeftMenu: typeof import('./src/components/Layout/components/LeftMenu/index.vue')['default']
    Logo: typeof import('./src/components/Layout/components/Header/comp/Logo.vue')['default']
    Menu: typeof import('./src/components/Layout/components/LeftMenu/comp/Menu.vue')['default']
    RightContent: typeof import('./src/components/Layout/components/RightContent/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/Layout/components/Header/comp/Setting.vue')['default']
    Status: typeof import('./src/components/Layout/components/RightContent/comp/Status.vue')['default']
  }
}
